export const REFERENTIEL_METIER = {
  meta: {
    id: 'REFERENTIEL_METIER_CAP_DECISION_FT',
    nom: 'Referentiel metier Cap Decision FT',
    description: 'Referentiel central des catalogues et des regles metier de l application.',
    version: '1.0.0',
    origine: 'Referentiel Cap Decision FT',
    mainteneur: 'Equipe metier Cap Decision FT',
    derniereMiseAJour: '2026-07-18',
    statut: 'actif',
  },

  catalogues: {
    portefeuilles: {
      PORTEFEUILLE_MUTUALISE: {
        id: 'PORTEFEUILLE_MUTUALISE',
        libelle: 'Portefeuille Mutualise',
        description: 'Nouveaux inscrits ou situations en attente de qualification fine.',
      },
      PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI: {
        id: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
        libelle: 'Portefeuille Retour Rapide Emploi',
        description: 'Public en capacite de retour rapide a l emploi.',
      },
      PORTEFEUILLE_SOCIO_PROFESSIONNEL: {
        id: 'PORTEFEUILLE_SOCIO_PROFESSIONNEL',
        libelle: 'Portefeuille Socio-Professionnel',
        description: 'Public necessitant un accompagnement renforce.',
      },
      PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL: {
        id: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
        libelle: 'Portefeuille Accompagnement Global',
        description: 'Freins sociaux et professionnels imbriques.',
      },
      PORTEFEUILLE_TRAVAILLEUR_HANDICAPE: {
        id: 'PORTEFEUILLE_TRAVAILLEUR_HANDICAPE',
        libelle: 'Portefeuille Travailleur Handicape',
        description: 'Situations RQTH ou besoins de compensation.',
      },
      PORTEFEUILLE_PRE_ORIENTATION: {
        id: 'PORTEFEUILLE_PRE_ORIENTATION',
        libelle: 'Portefeuille Pre-Orientation',
        description: 'Projet a clarifier ou transition professionnelle.',
      },
      PORTEFEUILLE_CONTRAT_ENGAGEMENT_JEUNE: {
        id: 'PORTEFEUILLE_CONTRAT_ENGAGEMENT_JEUNE',
        libelle: 'Portefeuille Contrat Engagement Jeune',
        description: 'Jeunes avec accompagnement intensif.',
      },
      PORTEFEUILLE_INTENSIF: {
        id: 'PORTEFEUILLE_INTENSIF',
        libelle: 'Portefeuille Intensif',
        description: 'Suivi rapproche avec objectifs court terme.',
      },
    },

    niveauxAutonomie: {
      AUTONOMIE_FAIBLE: {
        id: 'AUTONOMIE_FAIBLE',
        libelle: 'Autonomie faible',
        description: 'Besoin d appui frequent dans les demarches.',
      },
      AUTONOMIE_MOYENNE: {
        id: 'AUTONOMIE_MOYENNE',
        libelle: 'Autonomie moyenne',
        description: 'Capacite partielle avec points de blocage ponctuels.',
      },
      AUTONOMIE_ELEVEE: {
        id: 'AUTONOMIE_ELEVEE',
        libelle: 'Autonomie elevee',
        description: 'Capacite a conduire les demarches en grande autonomie.',
      },
    },

    niveauxEmployabilite: {
      EMPLOYABILITE_FAIBLE: {
        id: 'EMPLOYABILITE_FAIBLE',
        libelle: 'Employabilite faible',
        description: 'Distance importante a l emploi.',
      },
      EMPLOYABILITE_MOYENNE: {
        id: 'EMPLOYABILITE_MOYENNE',
        libelle: 'Employabilite moyenne',
        description: 'Potentiel present avec besoin de consolidation.',
      },
      EMPLOYABILITE_FORTE: {
        id: 'EMPLOYABILITE_FORTE',
        libelle: 'Employabilite forte',
        description: 'Potentiel de retour rapide sous reserve de suivi adapte.',
      },
    },

    niveauxMotivation: {
      MOTIVATION_FAIBLE: {
        id: 'MOTIVATION_FAIBLE',
        libelle: 'Motivation faible',
        description: 'Mobilisation fragile et irréguliere.',
      },
      MOTIVATION_MOYENNE: {
        id: 'MOTIVATION_MOYENNE',
        libelle: 'Motivation moyenne',
        description: 'Mobilisation presente mais a consolider.',
      },
      MOTIVATION_ELEVEE: {
        id: 'MOTIVATION_ELEVEE',
        libelle: 'Motivation elevee',
        description: 'Mobilisation forte et orientee action.',
      },
    },

    niveauxUrgence: {
      URGENCE_FAIBLE: {
        id: 'URGENCE_FAIBLE',
        libelle: 'Urgence faible',
        description: 'Suivi standard.',
      },
      URGENCE_MOYENNE: {
        id: 'URGENCE_MOYENNE',
        libelle: 'Urgence moyenne',
        description: 'Suivi active avec point de vigilance.',
      },
      URGENCE_HAUTE: {
        id: 'URGENCE_HAUTE',
        libelle: 'Urgence haute',
        description: 'Actions prioritaires a engager rapidement.',
      },
      URGENCE_CRITIQUE: {
        id: 'URGENCE_CRITIQUE',
        libelle: 'Urgence critique',
        description: 'Intervention immediate et coordination renforcée.',
      },
    },

    typesFreins: {
      FREIN_PROJET: { id: 'FREIN_PROJET', libelle: 'Frein projet', description: 'Projet non clarifie ou instable.' },
      FREIN_MOBILITE: { id: 'FREIN_MOBILITE', libelle: 'Frein mobilite', description: 'Contraintes de deplacement.' },
      FREIN_SANTE: { id: 'FREIN_SANTE', libelle: 'Frein sante', description: 'Etat de sante impactant la disponibilite.' },
      FREIN_SOCIAL: { id: 'FREIN_SOCIAL', libelle: 'Frein social', description: 'Contraintes logement, droits, budget, etc.' },
      FREIN_NUMERIQUE: { id: 'FREIN_NUMERIQUE', libelle: 'Frein numerique', description: 'Difficulte dans les usages digitaux.' },
      FREIN_LINGUISTIQUE: { id: 'FREIN_LINGUISTIQUE', libelle: 'Frein linguistique', description: 'Maitrise insuffisante du francais.' },
      FREIN_MOTIVATION: { id: 'FREIN_MOTIVATION', libelle: 'Frein motivation', description: 'Faible mobilisation dans les demarches.' },
      FREIN_COMPETENCES: { id: 'FREIN_COMPETENCES', libelle: 'Frein competences', description: 'Ecart competences/metier cible.' },
    },

    typesCompetences: {
      COMPETENCE_TECHNIQUE: { id: 'COMPETENCE_TECHNIQUE', libelle: 'Competence technique', description: 'Savoir-faire metier.' },
      COMPETENCE_TRANSVERSALE: { id: 'COMPETENCE_TRANSVERSALE', libelle: 'Competence transversale', description: 'Competence mobilisable multi-contextes.' },
      COMPETENCE_NUMERIQUE: { id: 'COMPETENCE_NUMERIQUE', libelle: 'Competence numerique', description: 'Usage outils et demarches numeriques.' },
      COMPETENCE_LINGUISTIQUE: { id: 'COMPETENCE_LINGUISTIQUE', libelle: 'Competence linguistique', description: 'Expression ecrite et orale en francais.' },
      COMPETENCE_RELATIONNELLE: { id: 'COMPETENCE_RELATIONNELLE', libelle: 'Competence relationnelle', description: 'Communication et cooperation.' },
    },

    typesMobilite: {
      MOBILITE_AUTONOME: { id: 'MOBILITE_AUTONOME', libelle: 'Mobilite autonome', description: 'Deplacements autonomes.' },
      MOBILITE_LIMITEE: { id: 'MOBILITE_LIMITEE', libelle: 'Mobilite limitee', description: 'Contraintes de deplacement ponctuelles.' },
      MOBILITE_BLOQUANTE: { id: 'MOBILITE_BLOQUANTE', libelle: 'Mobilite bloquante', description: 'Frein majeur au deplacement.' },
      MOBILITE_A_ADAPTER: { id: 'MOBILITE_A_ADAPTER', libelle: 'Mobilite a adapter', description: 'Adaptations necessaires selon contexte.' },
    },

    typesFormation: {
      FORMATION_QUALIFIANTE: { id: 'FORMATION_QUALIFIANTE', libelle: 'Formation qualifiante', description: 'Formation certifiante/qualifiante.' },
      FORMATION_PREPARATOIRE: { id: 'FORMATION_PREPARATOIRE', libelle: 'Formation preparatoire', description: 'Mise a niveau avant parcours cible.' },
      FORMATION_RECONVERSION: { id: 'FORMATION_RECONVERSION', libelle: 'Formation reconversion', description: 'Transition vers nouveau metier.' },
      FORMATION_ADAPTEE_SANTE: { id: 'FORMATION_ADAPTEE_SANTE', libelle: 'Formation adaptee sante', description: 'Parcours adapte aux contraintes sante.' },
    },

    typesParcours: {
      PARCOURS_RETOUR_RAPIDE: { id: 'PARCOURS_RETOUR_RAPIDE', libelle: 'Parcours retour rapide', description: 'Insertion rapide sur le marche.' },
      PARCOURS_REMOBILISATION: { id: 'PARCOURS_REMOBILISATION', libelle: 'Parcours remobilisation', description: 'Remobilisation progressive.' },
      PARCOURS_RECONVERSION: { id: 'PARCOURS_RECONVERSION', libelle: 'Parcours reconversion', description: 'Transition professionnelle securisee.' },
      PARCOURS_INSERTION_GLOBALE: { id: 'PARCOURS_INSERTION_GLOBALE', libelle: 'Parcours insertion globale', description: 'Articulation social/professionnel.' },
      PARCOURS_HANDICAP: { id: 'PARCOURS_HANDICAP', libelle: 'Parcours handicap', description: 'Parcours adapte aux situations handicap.' },
      PARCOURS_JEUNE: { id: 'PARCOURS_JEUNE', libelle: 'Parcours jeune', description: 'Accompagnement intensif jeunes.' },
    },

    services: {
      SERVICE_CLARIFICATION_PROJET: {
        id: 'SERVICE_CLARIFICATION_PROJET',
        libelle: 'Clarification du projet professionnel',
        description: 'Aide a la formalisation du projet cible.',
      },
      SERVICE_VALORISATION_CV: {
        id: 'SERVICE_VALORISATION_CV',
        libelle: 'Valorisation CV',
        description: 'Mise a niveau des outils de candidature.',
      },
      SERVICE_RECHERCHE_ACTIVE_EMPLOI: {
        id: 'SERVICE_RECHERCHE_ACTIVE_EMPLOI',
        libelle: 'Recherche active d emploi',
        description: 'Pilotage des candidatures et relances.',
      },
      SERVICE_APPUI_NUMERIQUE: {
        id: 'SERVICE_APPUI_NUMERIQUE',
        libelle: 'Appui numerique',
        description: 'Renforcement autonomie numerique.',
      },
      SERVICE_APPUI_MOBILITE: {
        id: 'SERVICE_APPUI_MOBILITE',
        libelle: 'Appui mobilite',
        description: 'Levee des freins de deplacement.',
      },
      SERVICE_APPUI_FORMATION: {
        id: 'SERVICE_APPUI_FORMATION',
        libelle: 'Appui orientation formation',
        description: 'Structuration des parcours formation.',
      },
      SERVICE_APPUI_CREATION_ACTIVITE: {
        id: 'SERVICE_APPUI_CREATION_ACTIVITE',
        libelle: 'Appui creation/reprise activite',
        description: 'Accompagnement entrepreneurial.',
      },
      SERVICE_ACCOMPAGNEMENT_GLOBAL: {
        id: 'SERVICE_ACCOMPAGNEMENT_GLOBAL',
        libelle: 'Accompagnement global',
        description: 'Coordination social/professionnel.',
      },
    },

    prestations: {
      PRESTATION_ACTIV_PROJET: { id: 'PRESTATION_ACTIV_PROJET', libelle: "Activ'Projet", description: 'Clarification de projet.' },
      PRESTATION_ACTIV_CREA: { id: 'PRESTATION_ACTIV_CREA', libelle: "Activ'Crea", description: 'Creation/reprise activite.' },
      PRESTATION_PERIODE_MISE_EN_SITUATION_PROFESSIONNELLE: { id: 'PRESTATION_PERIODE_MISE_EN_SITUATION_PROFESSIONNELLE', libelle: 'PMSMP', description: 'Immersion professionnelle.' },
      PRESTATION_CONTRAT_ENGAGEMENT_JEUNE: { id: 'PRESTATION_CONTRAT_ENGAGEMENT_JEUNE', libelle: 'CEJ', description: 'Contrat engagement jeune.' },
      PRESTATION_AIDE_MOBILITE: { id: 'PRESTATION_AIDE_MOBILITE', libelle: 'Aide a la mobilite', description: 'Soutien mobilite.' },
      PRESTATION_ACCOMPAGNEMENT_GLOBAL: { id: 'PRESTATION_ACCOMPAGNEMENT_GLOBAL', libelle: 'Accompagnement Global', description: 'Suivi global.' },
      PRESTATION_PASS_IAE: { id: 'PRESTATION_PASS_IAE', libelle: 'PASS IAE', description: 'Orientation insertion activite economique.' },
      PRESTATION_EMPLOI_ACCOMPAGNE: { id: 'PRESTATION_EMPLOI_ACCOMPAGNE', libelle: 'Emploi accompagne', description: 'Accompagnement emploi adapte.' },
      PRESTATION_BILAN_COMPETENCES: { id: 'PRESTATION_BILAN_COMPETENCES', libelle: 'Bilan de competences', description: 'Analyse competences/transitions.' },
      PRESTATION_PARCOURS_EMPLOI_SANTE: { id: 'PRESTATION_PARCOURS_EMPLOI_SANTE', libelle: 'Parcours Emploi Sante', description: 'Coordination sante-emploi.' },
      PRESTATION_TECHNIQUES_RECHERCHE_EMPLOI: { id: 'PRESTATION_TECHNIQUES_RECHERCHE_EMPLOI', libelle: "Techniques de recherche d'emploi", description: 'Methodologie recherche active.' },
      PRESTATION_PRESTATIONS_CAP_EMPLOI: { id: 'PRESTATION_PRESTATIONS_CAP_EMPLOI', libelle: 'Prestations Cap Emploi', description: 'Appui specialisé handicap.' },
    },

    ateliers: {
      ATELIER_CREATION_CV: { id: 'ATELIER_CREATION_CV', libelle: 'Creation CV', description: 'Construction ou mise a jour CV.' },
      ATELIER_BONNES_PRATIQUES_CV: { id: 'ATELIER_BONNES_PRATIQUES_CV', libelle: 'Les bonnes pratiques CV', description: 'Optimisation candidature.' },
      ATELIER_MON_MARCHE_DU_TRAVAIL: { id: 'ATELIER_MON_MARCHE_DU_TRAVAIL', libelle: 'Mon Marche du Travail', description: 'Connaissance marche local.' },
      ATELIER_PIX_EMPLOI: { id: 'ATELIER_PIX_EMPLOI', libelle: 'PIX Emploi', description: 'Autonomie numerique emploi.' },
      ATELIER_FOCUS_COMPETENCES: { id: 'ATELIER_FOCUS_COMPETENCES', libelle: 'Focus Competences', description: 'Identification des competences.' },
      ATELIER_DECOUVERTE_IMMERSION_FACILITEE: { id: 'ATELIER_DECOUVERTE_IMMERSION_FACILITEE', libelle: "Decouvrez l'immersion facilitee", description: 'Presentation immersion pro.' },
      ATELIER_PRESENTATION_ACTIV_PROJET: { id: 'ATELIER_PRESENTATION_ACTIV_PROJET', libelle: "Presentation Activ'Projet", description: 'Presentation dispositif projet.' },
      ATELIER_LUNDIS_ENTREPRENEURIAT: { id: 'ATELIER_LUNDIS_ENTREPRENEURIAT', libelle: "Les Lundis de l'entrepreneuriat", description: 'Atelier creation activite.' },
      ATELIER_360: { id: 'ATELIER_360', libelle: 'Atelier 360', description: 'Vision globale freins/atouts.' },
      ATELIER_360_SENIORS: { id: 'ATELIER_360_SENIORS', libelle: 'Atelier 360 Seniors', description: 'Repositionnement public senior.' },
    },

    formations: {
      FORMATION_PREPA_COMPETENCES: { id: 'FORMATION_PREPA_COMPETENCES', libelle: 'Prepa Competences', description: 'Montee en competences de base.' },
      FORMATION_PREPARATION_A_LA_FORMATION: { id: 'FORMATION_PREPARATION_A_LA_FORMATION', libelle: 'Preparation a la formation', description: 'Preparation entree formation.' },
      FORMATION_ACTION_FORMATION_CONVENTIONNEE: { id: 'FORMATION_ACTION_FORMATION_CONVENTIONNEE', libelle: 'AFC', description: 'Action de formation conventionnee.' },
      FORMATION_AIDE_INDIVIDUELLE_A_LA_FORMATION: { id: 'FORMATION_AIDE_INDIVIDUELLE_A_LA_FORMATION', libelle: 'AIF', description: 'Aide individuelle a la formation.' },
      FORMATION_VALIDATION_ACQUIS_EXPERIENCE: { id: 'FORMATION_VALIDATION_ACQUIS_EXPERIENCE', libelle: 'VAE', description: 'Validation acquis experience.' },
      FORMATION_PREPARATION_OPERATIONNELLE_EMPLOI_INDIVIDUELLE: { id: 'FORMATION_PREPARATION_OPERATIONNELLE_EMPLOI_INDIVIDUELLE', libelle: 'POEI', description: 'Preparation operationnelle emploi individuelle.' },
      FORMATION_ACTION_FORMATION_PREALABLE_RECRUTEMENT: { id: 'FORMATION_ACTION_FORMATION_PREALABLE_RECRUTEMENT', libelle: 'AFPR', description: 'Action prealable recrutement.' },
      FORMATION_FRANCAIS_LANGUE_ETRANGERE: { id: 'FORMATION_FRANCAIS_LANGUE_ETRANGERE', libelle: 'FLE', description: 'Renforcement linguistique.' },
      FORMATION_REMISE_A_NIVEAU_NUMERIQUE: { id: 'FORMATION_REMISE_A_NIVEAU_NUMERIQUE', libelle: 'Remise a niveau numerique', description: 'Competences numeriques de base.' },
    },

    partenaires: {
      PARTENAIRE_FRANCE_TRAVAIL_AJACCIO: { id: 'PARTENAIRE_FRANCE_TRAVAIL_AJACCIO', libelle: 'France Travail Ajaccio', description: 'Agence de reference locale.' },
      PARTENAIRE_CAP_EMPLOI_CORSE: { id: 'PARTENAIRE_CAP_EMPLOI_CORSE', libelle: 'Cap Emploi Corse', description: 'Partenaire handicap emploi.' },
      PARTENAIRE_MISSION_LOCALE_AJACCIO: { id: 'PARTENAIRE_MISSION_LOCALE_AJACCIO', libelle: 'Mission Locale Ajaccio', description: 'Accompagnement jeunes.' },
      PARTENAIRE_AFPA_CORSE: { id: 'PARTENAIRE_AFPA_CORSE', libelle: 'AFPA Corse', description: 'Organisme formation.' },
      PARTENAIRE_BGE_CORSE: { id: 'PARTENAIRE_BGE_CORSE', libelle: 'BGE Corse', description: 'Appui creation/reprise.' },
      PARTENAIRE_CIBC_CORSE: { id: 'PARTENAIRE_CIBC_CORSE', libelle: 'CIBC Corse', description: 'Bilan et transition professionnelle.' },
      PARTENAIRE_CIDFF_CORSE_DU_SUD: { id: 'PARTENAIRE_CIDFF_CORSE_DU_SUD', libelle: 'CIDFF Corse-du-Sud', description: 'Appui droits et accompagnement social.' },
      PARTENAIRE_CARSAT_CORSE: { id: 'PARTENAIRE_CARSAT_CORSE', libelle: 'CARSAT Corse', description: 'Appui senior/sante/retraite.' },
      PARTENAIRE_CAF_CORSE_DU_SUD: { id: 'PARTENAIRE_CAF_CORSE_DU_SUD', libelle: 'CAF Corse-du-Sud', description: 'Appui social et prestations.' },
      PARTENAIRE_CPAM_CORSE_DU_SUD: { id: 'PARTENAIRE_CPAM_CORSE_DU_SUD', libelle: 'CPAM Corse-du-Sud', description: 'Appui parcours sante.' },
      PARTENAIRE_MDPH_CORSE: { id: 'PARTENAIRE_MDPH_CORSE', libelle: 'MDPH Corse', description: 'Orientation compensation handicap.' },
      PARTENAIRE_COLLECTIVITE_CORSE: { id: 'PARTENAIRE_COLLECTIVITE_CORSE', libelle: 'Collectivite de Corse', description: 'Coordination insertion territoriale.' },
      PARTENAIRE_CCI_CORSE: { id: 'PARTENAIRE_CCI_CORSE', libelle: "Chambre de Commerce et d'Industrie de Corse", description: 'Appui projets entrepreneuriaux.' },
      PARTENAIRE_CMA_CORSE: { id: 'PARTENAIRE_CMA_CORSE', libelle: "Chambre de Metiers et de l'Artisanat de Corse", description: 'Appui parcours artisanat.' },
      PARTENAIRE_STRUCTURES_IAE_CORSE_DU_SUD: { id: 'PARTENAIRE_STRUCTURES_IAE_CORSE_DU_SUD', libelle: 'Structures IAE Corse-du-Sud', description: 'Insertion activite economique.' },
    },

    prescriptions: {
      PRESCRIPTION_ACTIV_PROJET: { id: 'PRESCRIPTION_ACTIV_PROJET', libelle: "Activ'Projet", description: 'Prescription clarification projet.' },
      PRESCRIPTION_ACTIV_CREA: { id: 'PRESCRIPTION_ACTIV_CREA', libelle: "Activ'Crea", description: 'Prescription creation activite.' },
      PRESCRIPTION_PMSMP: { id: 'PRESCRIPTION_PMSMP', libelle: 'PMSMP', description: 'Prescription immersion professionnelle.' },
      PRESCRIPTION_CEJ: { id: 'PRESCRIPTION_CEJ', libelle: 'CEJ', description: 'Prescription CEJ.' },
      PRESCRIPTION_AIDE_MOBILITE: { id: 'PRESCRIPTION_AIDE_MOBILITE', libelle: 'Aide a la mobilite', description: 'Prescription mobilite.' },
      PRESCRIPTION_ACCOMPAGNEMENT_GLOBAL: { id: 'PRESCRIPTION_ACCOMPAGNEMENT_GLOBAL', libelle: 'Accompagnement Global', description: 'Prescription coordination globale.' },
      PRESCRIPTION_PASS_IAE: { id: 'PRESCRIPTION_PASS_IAE', libelle: 'PASS IAE', description: 'Prescription IAE.' },
      PRESCRIPTION_EMPLOI_ACCOMPAGNE: { id: 'PRESCRIPTION_EMPLOI_ACCOMPAGNE', libelle: 'Emploi accompagne', description: 'Prescription adaptation handicap.' },
    },
  },

  gabaritsSynthese: {
    introduction: [
      'Vous m indiquez...',
      'Vous precisez...',
      'Je reprends avec vous les elements de situation.',
    ],
    situation: [
      'Situation administrative et personnelle',
      'Contexte d accompagnement actuel',
      'Points de vigilance immediats',
    ],
    projet: [
      'Vous souhaitez...',
      'Nous convenons de clarifier/valider le projet.',
      'Positionnement metier cible',
    ],
    competences: [
      'Competences mobilisables',
      'Competences a renforcer',
      'Actions de valorisation',
    ],
    freins: [
      'Freins identifies',
      'Levee de freins prioritaire',
      'Coordination des partenaires',
    ],
    mobilite: [
      'Mobilite actuelle',
      'Contraintes de deplacement',
      'Solutions mobilisables',
    ],
    formation: [
      'Pistes de formation',
      'Prerequis a verifier',
      'Financement et calendrier',
    ],
    actions: [
      'Je vous oriente...',
      'Je vous prescris...',
      'Nous convenons des prochaines etapes.',
    ],
    conclusion: [
      'Synthese des decisions',
      'Echeance de suivi',
      'Verification de la mise en oeuvre',
    ],
  },

  map: {
    objectifs: [
      {
        id: 'MAP_OBJECTIF_CLARIFIER_PROJET',
        libelle: 'Clarifier le projet professionnel',
        description: 'Structurer un projet cible coherent.',
      },
      {
        id: 'MAP_OBJECTIF_LEVER_FREINS',
        libelle: 'Lever les freins prioritaires',
        description: 'Prioriser les freins bloquants.',
      },
      {
        id: 'MAP_OBJECTIF_RENFORCER_AUTONOMIE',
        libelle: 'Renforcer l autonomie de recherche d emploi',
        description: 'Developper autonomie dans les demarches.',
      },
      {
        id: 'MAP_OBJECTIF_SECURISER_FORMATION',
        libelle: 'Securiser une solution de formation ou immersion',
        description: 'Valider parcours de montee en competences.',
      },
    ],
    indicateurs: [
      {
        id: 'MAP_INDICATEUR_NOMBRE_DEMARCHES',
        libelle: 'Nombre de demarches realisees',
        description: 'Demarches effectuees entre deux suivis.',
      },
      {
        id: 'MAP_INDICATEUR_EVOLUTION_AUTONOMIE',
        libelle: 'Evolution de l autonomie',
        description: 'Progression percue de l autonomie.',
      },
      {
        id: 'MAP_INDICATEUR_ACTIONS_PLANIFIEES',
        libelle: 'Realisation des actions planifiees',
        description: 'Taux d actions executees.',
      },
      {
        id: 'MAP_INDICATEUR_REDUCTION_FREINS',
        libelle: 'Reduction des freins identifies',
        description: 'Freins leves ou attenues.',
      },
    ],
    echeances: [
      { id: 'MAP_ECHEANCE_7_JOURS', libelle: 'Sous 7 jours', description: 'Suivi tres rapproche.' },
      { id: 'MAP_ECHEANCE_15_JOURS', libelle: 'Sous 15 jours', description: 'Suivi prioritaire.' },
      { id: 'MAP_ECHEANCE_30_JOURS', libelle: 'Sous 30 jours', description: 'Suivi standard actif.' },
      { id: 'MAP_ECHEANCE_45_JOURS', libelle: 'Sous 45 jours', description: 'Suivi standard.' },
    ],
  },

  diagnostic: {
    dimensions: {
      autonomie: {
        id: 'DIAGNOSTIC_DIMENSION_AUTONOMIE',
        description: 'Capacite du demandeur a realiser ses demarches.',
        niveaux: ['AUTONOMIE_FAIBLE', 'AUTONOMIE_MOYENNE', 'AUTONOMIE_ELEVEE'],
      },
      distanceEmploi: {
        id: 'DIAGNOSTIC_DIMENSION_DISTANCE_EMPLOI',
        description: 'Distance estimee a l emploi.',
        niveaux: ['DISTANCE_EMPLOI_FAIBLE', 'DISTANCE_EMPLOI_MOYENNE', 'DISTANCE_EMPLOI_ELEVEE'],
      },
      maturiteProjet: {
        id: 'DIAGNOSTIC_DIMENSION_MATURITE_PROJET',
        description: 'Niveau de maturite du projet professionnel.',
        niveaux: ['MATURITE_PROJET_FAIBLE', 'MATURITE_PROJET_MOYENNE', 'MATURITE_PROJET_ELEVEE'],
      },
      employabilite: {
        id: 'DIAGNOSTIC_DIMENSION_EMPLOYABILITE',
        description: 'Potentiel global de retour a l emploi.',
        niveaux: ['EMPLOYABILITE_FAIBLE', 'EMPLOYABILITE_MOYENNE', 'EMPLOYABILITE_FORTE'],
      },
      urgence: {
        id: 'DIAGNOSTIC_DIMENSION_URGENCE',
        description: 'Niveau de priorisation de l accompagnement.',
        niveaux: ['URGENCE_FAIBLE', 'URGENCE_MOYENNE', 'URGENCE_HAUTE', 'URGENCE_CRITIQUE'],
      },
    },
    vigilanceStandards: [
      'Verifier les informations manquantes',
      'Prioriser la levee des freins bloquants',
      'Securiser la coherence entre projet et actions',
      'Fixer une echeance de suivi explicite',
    ],
    version: '1.0.0',
    origine: 'Referentiel Cap Decision FT',
  },

  reglesDecision: [
    {
      id: 'REGLE_001_PROJET_FLOU_SANS_CIBLE_METIER',
      nom: 'Projet flou sans cible metier',
      description: 'Projet non formalise et non mature.',
      domaine: 'projet professionnel',
      conditions: { projetMature: false, projetFormalise: false },
      actions: {
        objectifPrioritaire: 'Clarifier le projet',
        prestationsIds: ['PRESTATION_ACTIV_PROJET', 'PRESTATION_BILAN_COMPETENCES'],
        ateliersIds: ['ATELIER_MON_MARCHE_DU_TRAVAIL'],
        portefeuilleId: 'PORTEFEUILLE_PRE_ORIENTATION',
      },
      explication: 'Un projet flou requiert une phase de clarification avant orientation cible.',
      priorite: 95,
      poids: 1.0,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_002_PROJET_VALIDE_RECHERCHE_ACTIVE',
      nom: 'Projet valide avec recherche active',
      description: 'Projet mature et dynamique active.',
      domaine: 'recherche emploi',
      conditions: { projetMature: true, rechercheActive: true },
      actions: {
        objectifPrioritaire: 'Accelerer le retour a l emploi',
        ateliersIds: ['ATELIER_CREATION_CV', 'ATELIER_BONNES_PRATIQUES_CV'],
        formationsIds: ['FORMATION_PREPARATION_OPERATIONNELLE_EMPLOI_INDIVIDUELLE'],
        portefeuilleId: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
      },
      explication: 'Le projet valide permet de focaliser sur les actions de placement rapide.',
      priorite: 88,
      poids: 0.95,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_003_CV_ANCIEN_OU_NON_ADAPTE',
      nom: 'CV ancien ou non adapte',
      description: 'Outils candidature a actualiser.',
      domaine: 'recherche emploi',
      conditions: { cvAncien: true },
      actions: {
        objectifPrioritaire: 'Actualiser les outils de candidature',
        servicesIds: ['SERVICE_VALORISATION_CV'],
        ateliersIds: ['ATELIER_CREATION_CV', 'ATELIER_BONNES_PRATIQUES_CV'],
      },
      explication: 'Un CV non adapte freine directement les candidatures.',
      priorite: 84,
      poids: 0.8,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_004_ABSENCE_CV_EXPLOITABLE',
      nom: 'Absence de CV exploitable',
      description: 'CV absent/non visible.',
      domaine: 'recherche emploi',
      conditions: { cvVisible: false },
      actions: {
        objectifPrioritaire: 'Construire un CV cible',
        ateliersIds: ['ATELIER_CREATION_CV', 'ATELIER_MON_MARCHE_DU_TRAVAIL'],
      },
      explication: 'Sans CV exploitable, la mise en relation est limitee.',
      priorite: 90,
      poids: 0.92,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_005_FREIN_MOBILITE_PRINCIPAL',
      nom: 'Frein mobilite principal',
      description: 'Mobilite blocante dans le parcours.',
      domaine: 'mobilite',
      conditions: { freinMobilite: true },
      actions: {
        objectifPrioritaire: 'Lever le frein de deplacement',
        prestationsIds: ['PRESTATION_AIDE_MOBILITE', 'PRESTATION_PERIODE_MISE_EN_SITUATION_PROFESSIONNELLE'],
        partenairesIds: ['PARTENAIRE_COLLECTIVITE_CORSE'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'Le frein mobilite doit etre traite pour rendre les actions realisables.',
      priorite: 92,
      poids: 0.9,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_006_FREINS_SOCIAUX_CUMULES',
      nom: 'Freins sociaux cumules',
      description: 'Freins multiples d insertion.',
      domaine: 'freins',
      conditions: { freinsMultiples: true },
      actions: {
        objectifPrioritaire: 'Coordonner accompagnement global',
        prestationsIds: ['PRESTATION_ACCOMPAGNEMENT_GLOBAL'],
        ateliersIds: ['ATELIER_360'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'La coordination globale est necessaire pour lever plusieurs freins simultanes.',
      priorite: 96,
      poids: 1.0,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_007_FREIN_NUMERIQUE_ELEVE',
      nom: 'Frein numerique eleve',
      description: 'Autonomie numerique insuffisante.',
      domaine: 'autonomie',
      conditions: { autonomieNumeriqueFaible: true },
      actions: {
        objectifPrioritaire: 'Renforcer autonomie numerique',
        ateliersIds: ['ATELIER_PIX_EMPLOI'],
        formationsIds: ['FORMATION_REMISE_A_NIVEAU_NUMERIQUE'],
        portefeuilleId: 'PORTEFEUILLE_SOCIO_PROFESSIONNEL',
      },
      explication: 'L autonomie numerique conditionne les demarches emploi.',
      priorite: 86,
      poids: 0.85,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_008_PROJET_ORIENTABLE_FORMATION',
      nom: 'Projet orientable formation',
      description: 'Besoin de formation avec projet mature.',
      domaine: 'formation',
      conditions: { besoinFormation: true, projetMature: true },
      actions: {
        objectifPrioritaire: 'Securiser entree en formation',
        formationsIds: ['FORMATION_AIDE_INDIVIDUELLE_A_LA_FORMATION', 'FORMATION_ACTION_FORMATION_CONVENTIONNEE', 'FORMATION_PREPARATION_A_LA_FORMATION'],
        partenairesIds: ['PARTENAIRE_AFPA_CORSE'],
        portefeuilleId: 'PORTEFEUILLE_PRE_ORIENTATION',
      },
      explication: 'Le projet est defini mais necessite des competences additionnelles.',
      priorite: 91,
      poids: 0.9,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_009_JEUNE_ACCOMPAGNEMENT_INTENSIF',
      nom: 'Jeune avec besoin d accompagnement intensif',
      description: 'Public jeune avec besoin de cadre renforce.',
      domaine: 'accompagnement',
      conditions: { ageInferieur26: true, besoinCadreIntensif: true },
      actions: {
        objectifPrioritaire: 'Structurer un parcours CEJ',
        prestationsIds: ['PRESTATION_CONTRAT_ENGAGEMENT_JEUNE'],
        ateliersIds: ['ATELIER_CREATION_CV'],
        partenairesIds: ['PARTENAIRE_MISSION_LOCALE_AJACCIO'],
        portefeuilleId: 'PORTEFEUILLE_CONTRAT_ENGAGEMENT_JEUNE',
      },
      explication: 'Le CEJ apporte un cadre de suivi adapte aux jeunes.',
      priorite: 89,
      poids: 0.87,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_010_PUBLIC_SENIOR_REPOSITIONNEMENT',
      nom: 'Public senior a repositionner',
      description: 'Valorisation experience senior.',
      domaine: 'experience',
      conditions: { ageSuperieur50: true, projetMature: true },
      actions: {
        objectifPrioritaire: 'Valoriser experience et repositionnement',
        ateliersIds: ['ATELIER_360_SENIORS'],
        formationsIds: ['FORMATION_VALIDATION_ACQUIS_EXPERIENCE'],
        partenairesIds: ['PARTENAIRE_CARSAT_CORSE', 'PARTENAIRE_CIBC_CORSE'],
        portefeuilleId: 'PORTEFEUILLE_PRE_ORIENTATION',
      },
      explication: 'Le repositionnement senior s appuie sur la valorisation de l experience.',
      priorite: 82,
      poids: 0.78,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_011_HANDICAP_BESOIN_COMPENSATION',
      nom: 'Situation handicap avec besoin de compensation',
      description: 'Situation RQTH active.',
      domaine: 'RQTH',
      conditions: { rqth: true },
      actions: {
        objectifPrioritaire: 'Securiser adaptation du parcours',
        prestationsIds: ['PRESTATION_EMPLOI_ACCOMPAGNE', 'PRESTATION_PRESTATIONS_CAP_EMPLOI'],
        partenairesIds: ['PARTENAIRE_CAP_EMPLOI_CORSE', 'PARTENAIRE_MDPH_CORSE'],
        portefeuilleId: 'PORTEFEUILLE_TRAVAILLEUR_HANDICAPE',
      },
      explication: 'Le parcours doit integre les compensations necessaires.',
      priorite: 97,
      poids: 1.0,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_012_DEMARCHE_RQTH_EN_COURS',
      nom: 'Demarche RQTH en cours',
      description: 'Demande RQTH en instruction.',
      domaine: 'RQTH',
      conditions: { demandeRqthEnCours: true },
      actions: {
        objectifPrioritaire: 'Structurer les etapes de reconnaissance',
        prestationsIds: ['PRESTATION_ACCOMPAGNEMENT_GLOBAL'],
        partenairesIds: ['PARTENAIRE_MDPH_CORSE', 'PARTENAIRE_CAP_EMPLOI_CORSE'],
        portefeuilleId: 'PORTEFEUILLE_TRAVAILLEUR_HANDICAPE',
      },
      explication: 'La demarche doit etre suivie pour securiser l orientation future.',
      priorite: 93,
      poids: 0.92,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_013_CONTRAINTE_SANTE_DISPONIBILITE',
      nom: 'Contrainte sante impactant la disponibilite',
      description: 'Frein sante prioritaire.',
      domaine: 'sante',
      conditions: { freinSante: true },
      actions: {
        objectifPrioritaire: 'Adapter rythme d insertion',
        prestationsIds: ['PRESTATION_ACCOMPAGNEMENT_GLOBAL', 'PRESTATION_PARCOURS_EMPLOI_SANTE'],
        partenairesIds: ['PARTENAIRE_CPAM_CORSE_DU_SUD'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'Le rythme d insertion doit etre ajuste aux contraintes sante.',
      priorite: 95,
      poids: 0.94,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_014_PROJET_CREATION_ENTREPRISE',
      nom: 'Projet creation d entreprise',
      description: 'Projet entrepreneurial identifie.',
      domaine: 'projet professionnel',
      conditions: { projetCreationEntreprise: true },
      actions: {
        objectifPrioritaire: 'Structurer projet entrepreneurial',
        prestationsIds: ['PRESTATION_ACTIV_CREA'],
        ateliersIds: ['ATELIER_LUNDIS_ENTREPRENEURIAT'],
        partenairesIds: ['PARTENAIRE_BGE_CORSE', 'PARTENAIRE_CCI_CORSE'],
        portefeuilleId: 'PORTEFEUILLE_SOCIO_PROFESSIONNEL',
      },
      explication: 'Un projet entrepreneurial requiert un accompagnement specialise.',
      priorite: 85,
      poids: 0.83,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_015_PROJET_ARTISANAL',
      nom: 'Projet artisanal',
      description: 'Orientation artisanat.',
      domaine: 'projet professionnel',
      conditions: { projetArtisanat: true },
      actions: {
        objectifPrioritaire: 'Qualifier le parcours artisanal',
        prestationsIds: ['PRESTATION_ACTIV_CREA'],
        partenairesIds: ['PARTENAIRE_CMA_CORSE'],
      },
      explication: 'Le projet artisanal necessite un appui consulaire specifique.',
      priorite: 80,
      poids: 0.76,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_016_RECONVERSION_ECART_COMPETENCES',
      nom: 'Reconversion avec ecart de competences',
      description: 'Transition professionnelle avec besoins de competences.',
      domaine: 'competences',
      conditions: { reconversion: true, ecartCompetencesEleve: true },
      actions: {
        objectifPrioritaire: 'Construire un plan de montee en competences',
        ateliersIds: ['ATELIER_FOCUS_COMPETENCES'],
        formationsIds: ['FORMATION_AIDE_INDIVIDUELLE_A_LA_FORMATION', 'FORMATION_ACTION_FORMATION_CONVENTIONNEE'],
        portefeuilleId: 'PORTEFEUILLE_PRE_ORIENTATION',
      },
      explication: 'La reconversion exige un plan de progression clair.',
      priorite: 88,
      poids: 0.86,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_017_MOTIVATION_FAIBLE',
      nom: 'Motivation faible a relancer',
      description: 'Mobilisation insuffisante.',
      domaine: 'motivation',
      conditions: { motivationFaible: true },
      actions: {
        objectifPrioritaire: 'Remobiliser la personne',
        ateliersIds: ['ATELIER_360', 'ATELIER_PRESENTATION_ACTIV_PROJET'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'Les actions de remobilisation sont prioritaires avant intensification.',
      priorite: 90,
      poids: 0.9,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_018_MOTIVATION_ELEVEE_DISPONIBILITE_CONFIRMEE',
      nom: 'Motivation elevee et disponibilite confirmee',
      description: 'Potentiel d acceleration.',
      domaine: 'motivation',
      conditions: { motivationElevee: true, disponibiliteImmediate: true },
      actions: {
        objectifPrioritaire: 'Declencher actions rapides',
        prestationsIds: ['PRESTATION_PERIODE_MISE_EN_SITUATION_PROFESSIONNELLE'],
        formationsIds: ['FORMATION_PREPARATION_OPERATIONNELLE_EMPLOI_INDIVIDUELLE'],
        ateliersIds: ['ATELIER_MON_MARCHE_DU_TRAVAIL'],
        portefeuilleId: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
      },
      explication: 'La motivation elevee permet de lancer des actions de resultat.',
      priorite: 83,
      poids: 0.79,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_019_EXPERIENCE_SIGNIFICATIVE_CIBLE_INCERTAINE',
      nom: 'Experience significative mais cible incertaine',
      description: 'Experience forte, projet a affiner.',
      domaine: 'experience',
      conditions: { experienceSignificative: true, projetMature: false },
      actions: {
        objectifPrioritaire: 'Repositionner experience',
        prestationsIds: ['PRESTATION_BILAN_COMPETENCES'],
        ateliersIds: ['ATELIER_FOCUS_COMPETENCES'],
        partenairesIds: ['PARTENAIRE_CIBC_CORSE'],
      },
      explication: 'Le repositionnement aide a traduire l experience en cible metier.',
      priorite: 81,
      poids: 0.75,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_020_PAS_EXPERIENCE_RECENTE',
      nom: 'Pas d experience recente',
      description: 'Besoin de validation terrain.',
      domaine: 'experience',
      conditions: { experienceRecenteAbsente: true },
      actions: {
        objectifPrioritaire: 'Valider aptitudes en situation',
        prestationsIds: ['PRESTATION_PERIODE_MISE_EN_SITUATION_PROFESSIONNELLE'],
        ateliersIds: ['ATELIER_DECOUVERTE_IMMERSION_FACILITEE'],
        portefeuilleId: 'PORTEFEUILLE_PRE_ORIENTATION',
      },
      explication: 'L immersion permet de confirmer aptitudes et projet.',
      priorite: 84,
      poids: 0.8,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_021_FREIN_LINGUISTIQUE',
      nom: 'Frein linguistique',
      description: 'Maitrise du francais insuffisante.',
      domaine: 'competences',
      conditions: { maitriseFrancaisInsuffisante: true },
      actions: {
        objectifPrioritaire: 'Renforcer comprehension et expression',
        formationsIds: ['FORMATION_FRANCAIS_LANGUE_ETRANGERE', 'FORMATION_REMISE_A_NIVEAU_NUMERIQUE'],
        portefeuilleId: 'PORTEFEUILLE_SOCIO_PROFESSIONNEL',
      },
      explication: 'Le renforcement linguistique conditionne l insertion durable.',
      priorite: 91,
      poids: 0.91,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_022_AUTONOMIE_ADMINISTRATIVE_FAIBLE',
      nom: 'Autonomie administrative faible',
      description: 'Demarches administratives fragiles.',
      domaine: 'autonomie',
      conditions: { autonomieAdministrativeFaible: true },
      actions: {
        objectifPrioritaire: 'Securiser les demarches obligatoires',
        prestationsIds: ['PRESTATION_ACCOMPAGNEMENT_GLOBAL'],
        ateliersIds: ['ATELIER_360'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'L accompagnement global permet de fiabiliser les obligations administratives.',
      priorite: 90,
      poids: 0.88,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_023_RECHERCHE_EMPLOI_INEXISTANTE',
      nom: 'Recherche emploi inexistante',
      description: 'Projet mature mais pas de dynamique active.',
      domaine: 'recherche emploi',
      conditions: { rechercheActive: false, projetMature: true },
      actions: {
        objectifPrioritaire: 'Relancer la dynamique de candidatures',
        prestationsIds: ['PRESTATION_TECHNIQUES_RECHERCHE_EMPLOI'],
        ateliersIds: ['ATELIER_MON_MARCHE_DU_TRAVAIL'],
        portefeuilleId: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
      },
      explication: 'La methode de recherche doit etre reactualisee rapidement.',
      priorite: 87,
      poids: 0.84,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_024_PROJET_VALIDE_BESOIN_TEST_TERRAIN',
      nom: 'Projet valide et besoin de test terrain',
      description: 'Projet mature a confirmer en immersion.',
      domaine: 'projet professionnel',
      conditions: { projetMature: true, besoinValidationTerrain: true },
      actions: {
        objectifPrioritaire: 'Confirmer la cible metier',
        prestationsIds: ['PRESTATION_PERIODE_MISE_EN_SITUATION_PROFESSIONNELLE'],
        ateliersIds: ['ATELIER_DECOUVERTE_IMMERSION_FACILITEE'],
        portefeuilleId: 'PORTEFEUILLE_PRE_ORIENTATION',
      },
      explication: 'Le test terrain valide la faisabilite du projet cible.',
      priorite: 82,
      poids: 0.79,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_025_PUBLIC_RSA_FREINS_SOCIAUX',
      nom: 'Public RSA avec freins sociaux',
      description: 'Freins sociaux dominants en situation RSA.',
      domaine: 'freins',
      conditions: { rsa: true, freinsSociaux: true },
      actions: {
        objectifPrioritaire: 'Coordonner insertion sociale et professionnelle',
        prestationsIds: ['PRESTATION_ACCOMPAGNEMENT_GLOBAL'],
        ateliersIds: ['ATELIER_360'],
        partenairesIds: ['PARTENAIRE_COLLECTIVITE_CORSE', 'PARTENAIRE_CAF_CORSE_DU_SUD'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'La coordination multi-acteurs est necessaire pour stabiliser la situation.',
      priorite: 94,
      poids: 0.96,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_026_BESOIN_ORIENTATION_IAE',
      nom: 'Besoin d orientation IAE',
      description: 'Besoin de parcours insertion progressive.',
      domaine: 'accompagnement',
      conditions: { besoinIAE: true },
      actions: {
        objectifPrioritaire: 'Structurer un parcours insertion progressive',
        prestationsIds: ['PRESTATION_PASS_IAE', 'PRESTATION_PERIODE_MISE_EN_SITUATION_PROFESSIONNELLE'],
        partenairesIds: ['PARTENAIRE_STRUCTURES_IAE_CORSE_DU_SUD'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'L IAE permet une progression vers l emploi durable.',
      priorite: 89,
      poids: 0.88,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_027_PROFIL_CADRE_REPOSITIONNEMENT',
      nom: 'Potentiel cadre a repositionner',
      description: 'Profil cadre en recherche active.',
      domaine: 'experience',
      conditions: { profilCadre: true, rechercheActive: true },
      actions: {
        objectifPrioritaire: 'Affiner positionnement marche',
        ateliersIds: ['ATELIER_BONNES_PRATIQUES_CV'],
        formationsIds: ['FORMATION_VALIDATION_ACQUIS_EXPERIENCE'],
        portefeuilleId: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
      },
      explication: 'Le repositionnement cadre requiert ciblage et valorisation.',
      priorite: 78,
      poids: 0.72,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_028_PROJET_FORMATION_SANS_PREREQUIS_VERIFIES',
      nom: 'Projet formation sans prerequis verifies',
      description: 'Prerequis formation non securises.',
      domaine: 'formation',
      conditions: { besoinFormation: true, prerequisFormationVerifies: false },
      actions: {
        objectifPrioritaire: 'Verifier prerequis et faisabilite',
        formationsIds: ['FORMATION_PREPARATION_A_LA_FORMATION', 'FORMATION_PREPA_COMPETENCES'],
      },
      explication: 'La verification des prerequis limite les ruptures de parcours.',
      priorite: 86,
      poids: 0.83,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_029_ATOUTS_ELEVES_FREINS_LIMITES',
      nom: 'Atouts eleves et freins limites',
      description: 'Contexte favorable a acceleration.',
      domaine: 'autonomie',
      conditions: { autonomieElevee: true, freinsMultiples: false },
      actions: {
        objectifPrioritaire: 'Accelerer mise en relation',
        formationsIds: ['FORMATION_PREPARATION_OPERATIONNELLE_EMPLOI_INDIVIDUELLE', 'FORMATION_ACTION_FORMATION_PREALABLE_RECRUTEMENT'],
        portefeuilleId: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
      },
      explication: 'Le contexte favorable autorise une strategie de placement rapide.',
      priorite: 77,
      poids: 0.7,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_030_COORDINATION_MEDICALE_EMPLOI',
      nom: 'Besoin de coordination medicale et emploi',
      description: 'Frein sante avec besoin de coordination parcours.',
      domaine: 'sante',
      conditions: { freinSante: true, besoinCoordinationParcours: true },
      actions: {
        objectifPrioritaire: 'Ajuster objectifs et rythme',
        prestationsIds: ['PRESTATION_PARCOURS_EMPLOI_SANTE', 'PRESTATION_ACCOMPAGNEMENT_GLOBAL'],
        partenairesIds: ['PARTENAIRE_CPAM_CORSE_DU_SUD', 'PARTENAIRE_CARSAT_CORSE'],
      },
      explication: 'La coordination medico-sociale soutient la continuite du parcours.',
      priorite: 93,
      poids: 0.93,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_031_PROJET_ENTREPRENEURIAL_BESOIN_FINANCEMENT',
      nom: 'Projet entrepreneurial avec besoin de financement',
      description: 'Creation d activite avec financement incertain.',
      domaine: 'projet professionnel',
      conditions: { projetCreationEntreprise: true, financementIncertain: true },
      actions: {
        objectifPrioritaire: 'Securiser la viabilite economique',
        prestationsIds: ['PRESTATION_ACTIV_CREA'],
        partenairesIds: ['PARTENAIRE_BGE_CORSE', 'PARTENAIRE_CCI_CORSE'],
      },
      explication: 'Le financement est un facteur critique de faisabilite.',
      priorite: 84,
      poids: 0.8,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_032_AUTONOME_SANS_ORIENTATION_FINALISEE',
      nom: 'Demandeur autonome sans orientation finalisee',
      description: 'Autonomie bonne mais cap non verrouille.',
      domaine: 'accompagnement',
      conditions: { autonomieElevee: true, orientationFinalisee: false },
      actions: {
        objectifPrioritaire: 'Finaliser le cap d orientation',
        ateliersIds: ['ATELIER_FOCUS_COMPETENCES', 'ATELIER_PRESENTATION_ACTIV_PROJET'],
        portefeuilleId: 'PORTEFEUILLE_PRE_ORIENTATION',
      },
      explication: 'L autonomie doit etre convertie en orientation cible explicite.',
      priorite: 76,
      poids: 0.68,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_033_PROJET_MATURE_OPPORTUNITE_EMPLOYEUR',
      nom: 'Projet mature avec opportunite employeur',
      description: 'Opportunite immediate a activer.',
      domaine: 'recherche emploi',
      conditions: { projetMature: true, opportuniteEmployeurIdentifiee: true },
      actions: {
        objectifPrioritaire: 'Activer la mise en relation immediate',
        formationsIds: ['FORMATION_PREPARATION_OPERATIONNELLE_EMPLOI_INDIVIDUELLE', 'FORMATION_ACTION_FORMATION_PREALABLE_RECRUTEMENT'],
        portefeuilleId: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
      },
      explication: 'La presence d opportunite requiert une activation rapide des leviers.',
      priorite: 85,
      poids: 0.82,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_034_BESOIN_REMOBILISATION_GLOBALE',
      nom: 'Besoin de remobilisation globale',
      description: 'Demobilisation ou rupture de dynamique.',
      domaine: 'freins',
      conditions: { demobilisation: true },
      actions: {
        objectifPrioritaire: 'Remobiliser progressivement',
        ateliersIds: ['ATELIER_360'],
        prestationsIds: ['PRESTATION_ACCOMPAGNEMENT_GLOBAL'],
        portefeuilleId: 'PORTEFEUILLE_ACCOMPAGNEMENT_GLOBAL',
      },
      explication: 'La remobilisation progressive est prealable a l intensification.',
      priorite: 92,
      poids: 0.91,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_035_COMPENSATIONS_HANDICAP_A_ACTUALISER',
      nom: 'Compensations handicap a actualiser',
      description: 'Besoins de compensation evolutifs.',
      domaine: 'RQTH',
      conditions: { rqth: true, compensationARevoir: true },
      actions: {
        objectifPrioritaire: 'Actualiser compensation et adaptation poste',
        prestationsIds: ['PRESTATION_PRESTATIONS_CAP_EMPLOI', 'PRESTATION_EMPLOI_ACCOMPAGNE'],
        partenairesIds: ['PARTENAIRE_CAP_EMPLOI_CORSE', 'PARTENAIRE_MDPH_CORSE'],
      },
      explication: 'L actualisation des compensations limite les ruptures de parcours.',
      priorite: 94,
      poids: 0.95,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_036_PARCOURS_COHERENT_A_CONSOLIDER',
      nom: 'Parcours coherent a consolider',
      description: 'Projet et dynamique coherents.',
      domaine: 'accompagnement',
      conditions: { projetMature: true, rechercheActive: true, freinsMultiples: false },
      actions: {
        objectifPrioritaire: 'Consolider strategie et suivi',
        ateliersIds: ['ATELIER_MON_MARCHE_DU_TRAVAIL'],
        portefeuilleId: 'PORTEFEUILLE_RETOUR_RAPIDE_EMPLOI',
      },
      explication: 'Le suivi doit maintenir la dynamique sans alourdir le parcours.',
      priorite: 72,
      poids: 0.65,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_037_MAP_LEVEE_DE_FREINS',
      nom: 'MAP orientee levee de freins',
      description: 'MAP priorisant freins bloquants.',
      domaine: 'MAP',
      conditions: { freinsMultiples: true, urgenceHaute: true },
      actions: {
        objectifPrioritaire: 'Structurer MAP de levee de freins',
        mapObjectifId: 'MAP_OBJECTIF_LEVER_FREINS',
        mapIndicateursIds: ['MAP_INDICATEUR_REDUCTION_FREINS', 'MAP_INDICATEUR_ACTIONS_PLANIFIEES'],
        mapEcheanceId: 'MAP_ECHEANCE_15_JOURS',
      },
      explication: 'La MAP doit traiter en premier les freins majeurs.',
      priorite: 98,
      poids: 1.0,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_038_MAP_INSERTION_RAPIDE',
      nom: 'MAP orientee insertion rapide',
      description: 'MAP orientee resultats emploi.',
      domaine: 'MAP',
      conditions: { projetMature: true, distanceEmploiFaible: true },
      actions: {
        objectifPrioritaire: 'Structurer MAP de retour rapide a l emploi',
        mapObjectifId: 'MAP_OBJECTIF_RENFORCER_AUTONOMIE',
        mapIndicateursIds: ['MAP_INDICATEUR_NOMBRE_DEMARCHES', 'MAP_INDICATEUR_ACTIONS_PLANIFIEES'],
        mapEcheanceId: 'MAP_ECHEANCE_30_JOURS',
      },
      explication: 'La MAP cible la concretisation des candidatures.',
      priorite: 79,
      poids: 0.74,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_039_ACCOMPAGNEMENT_RENFORCE_AUTONOMIE',
      nom: 'Accompagnement renforce sur autonomie',
      description: 'Autonomie faible avec besoin de suivi rapproche.',
      domaine: 'autonomie',
      conditions: { autonomieFaible: true, besoinSuiviRapproche: true },
      actions: {
        objectifPrioritaire: 'Mettre en place un suivi renforce',
        ateliersIds: ['ATELIER_360', 'ATELIER_PIX_EMPLOI'],
        portefeuilleId: 'PORTEFEUILLE_SOCIO_PROFESSIONNEL',
      },
      explication: 'Le suivi renforce soutient la progression de l autonomie.',
      priorite: 91,
      poids: 0.89,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
    {
      id: 'REGLE_040_ORIENTATION_PARTENAIRES_INSTITUTIONNELS',
      nom: 'Orientation partenaires institutionnels',
      description: 'Besoin d acces aux droits et stabilisation.',
      domaine: 'accompagnement',
      conditions: { besoinAccesDroits: true },
      actions: {
        objectifPrioritaire: 'Securiser acces aux droits et stabilite parcours',
        partenairesIds: ['PARTENAIRE_CIDFF_CORSE_DU_SUD', 'PARTENAIRE_CAF_CORSE_DU_SUD', 'PARTENAIRE_CPAM_CORSE_DU_SUD'],
        prestationsIds: ['PRESTATION_ACCOMPAGNEMENT_GLOBAL'],
      },
      explication: 'L acces aux droits est un prealable de stabilisation du parcours.',
      priorite: 90,
      poids: 0.88,
      version: '1.0.0',
      origine: 'Referentiel Cap Decision FT',
    },
  ],
}

export default REFERENTIEL_METIER
