export const connaissancesAteliers = [
	{
		id: 'CreationCV',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'BonnesPratiquesCV',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'MonMarcheDuTravail',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'DroitsEtEngagements',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'GestionDesDemarches',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'PIX',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'FocusCompetences',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'ImmersionFacilitee',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'PresentationActivProjet',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'LundisEntrepreneuriat',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'Atelier360',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
	{
		id: 'Atelier360Seniors',
		nom: '',
		description: '',
		objectif: '',
		public: '',
		obligatoire: '',
		conditions: [],
		contreIndications: [],
		portefeuilles: [],
		prestationsAssociees: [],
		partenaires: [],
		questionsAvantPrescription: [],
		documents: [],
		benefices: [],
		commentaires: '',
	},
]

export const ateliersCorse = [
	{
		id: "AC-CV",
		nom: "Creation CV",
		objectif: "Structurer un CV cible metier et valoriser les experiences.",
		public: "Demandeurs en recherche active sans CV a jour.",
		vigilance: "Verifier l'adequation du CV avec les offres locales.",
	},
	{
		id: "AC-BPCV",
		nom: "Les bonnes pratiques CV",
		objectif: "Ameliorer la lisibilite et l'impact des candidatures ecrites.",
		public: "Demandeurs souhaitant optimiser leurs outils de candidature.",
		vigilance: "Eviter les candidatures generiques non ciblees.",
	},
	{
		id: "AC-MMT",
		nom: "Mon Marche du Travail",
		objectif: "Identifier les opportunites locales par secteur et bassin.",
		public: "Demandeurs en phase de repositionnement professionnel.",
		vigilance: "Recouper projet, mobilite geographique et realites du marche corse.",
	},
	{
		id: "AC-PIX",
		nom: "PIX Emploi",
		objectif: "Renforcer les competences numeriques utiles aux demarches emploi.",
		public: "Demandeurs en difficulte avec les outils numeriques.",
		vigilance: "Prevoir un appui complementaire pour les publics peu autonomes.",
	},
	{
		id: "AC-360S",
		nom: "Atelier 360 Seniors",
		objectif: "Valoriser les competences des seniors et adapter la strategie de retour.",
		public: "Demandeurs de 50 ans et plus.",
		vigilance: "Lever les freins de representation age et actualiser le projet.",
	},
];
