export const opportunites = [
	{ nom: "AFPR", description: "Action de formation préalable au recrutement." },
	{ nom: "POEI", description: "Préparation opérationnelle à l'emploi individuelle." },
	{ nom: "PMSMP", description: "Période de mise en situation en milieu professionnel." },
	{ nom: "Activ Projet", description: "Accompagnement à la clarification du projet professionnel." },
	{ nom: "Activ Créa", description: "Accompagnement à la création ou reprise d'activité." },
	{ nom: "Prépa Compétences", description: "Parcours de remobilisation et construction de compétences." },
	{ nom: "Ambition Pro", description: "Dispositif de projection vers un emploi durable." },
	{ nom: "Un Emploi Stable", description: "Parcours orienté vers l'accès à un emploi pérenne." },
	{ nom: "AIF", description: "Aide individuelle au financement de la formation." },
	{ nom: "CPF", description: "Mobilisation du compte personnel de formation." },
	{ nom: "VAE", description: "Validation des acquis de l'expérience." },
	{ nom: "CEJ", description: "Contrat d'engagement jeune avec accompagnement renforcé." },
	{ nom: "MRS", description: "Méthode de recrutement par simulation." },
	{ nom: "Immersion", description: "Découverte métier via immersion en entreprise." },
	{ nom: "Mission Locale", description: "Relais d'accompagnement pour les jeunes publics." },
	{ nom: "Cap Emploi", description: "Accompagnement spécialisé pour les personnes en situation de handicap." },
	{ nom: "France Active", description: "Appui au financement et à la sécurisation des projets." },
	{ nom: "BGE", description: "Réseau d'accompagnement à la création d'entreprise." },
	{ nom: "CCI", description: "Appui consulaire pour projets et développement d'activité." },
	{ nom: "ADIE", description: "Microcrédit et accompagnement des entrepreneurs." },
	{ nom: "AGEFIPH", description: "Aides dédiées à l'emploi et à la formation des personnes handicapées." },
];
