export const portefeuilles = [
  {
    code: 'EM',
    nom: 'Emploi',
    description: 'Accompagnement orienté vers un retour rapide et durable à l’emploi.',
    objectif: 'Accélérer l’accès à l’emploi par des démarches ciblées, régulières et suivies.',
    public: 'Demandeur autonome, projet défini, disponibilité suffisante et freins limités ou maîtrisés.',
    criteres: ['Projet professionnel validé', 'Capacité à candidater', 'Mobilité compatible', 'Autonomie numérique suffisante'],
    accompagnement: 'Suivi centré sur les candidatures, les mises en relation, les immersions et les résultats obtenus.',
    actions: ['Actualiser le CV et le profil de compétences', 'Cibler les offres et entreprises', 'Mobiliser atelier, immersion ou prestation interne en priorité'],
    vigilance: 'Ne pas retenir ce portefeuille si un frein majeur empêche réellement les démarches.',
  },
  {
    code: 'INT',
    nom: 'Intensif',
    description: 'Accompagnement rapproché lorsque la situation exige des contacts et des actions fréquents.',
    objectif: 'Créer une dynamique soutenue avec des objectifs courts, mesurables et régulièrement réévalués.',
    public: 'Demandeur disponible ayant besoin d’un cadre renforcé pour structurer ou relancer son parcours.',
    criteres: ['Besoin de contacts fréquents', 'Démarches insuffisantes ou peu structurées', 'Objectifs à court terme nécessaires'],
    accompagnement: 'Étapes rapprochées, actions concrètes et vérification régulière des réalisations.',
    actions: ['Fixer 1 à 3 actions prioritaires', 'Prescrire un atelier ou une prestation adaptée', 'Mesurer le résultat avant d’ajuster le plan'],
    vigilance: 'Confirmer la disponibilité et l’adhésion du demandeur au rythme proposé.',
  },
  {
    code: 'MUT',
    nom: 'Mutualisé',
    description: 'Portefeuille transitoire pour les situations en attente d’analyse, de référent ou d’affectation stabilisée.',
    objectif: 'Sécuriser l’accueil et éviter qu’un dossier reste sans action pendant la phase d’orientation.',
    public: 'Nouveau demandeur, personne sans référent attribué ou situation dont le contrat d’engagement et l’orientation restent à formaliser.',
    criteres: ['Diagnostic non finalisé', 'Référent non attribué', 'Contrat d’engagement à formaliser', 'Orientation à arbitrer'],
    accompagnement: 'Traitement des urgences, premier diagnostic et préparation de l’affectation la plus adaptée.',
    actions: ['Compléter les données essentielles', 'Traiter les alertes prioritaires', 'Demander l’affectation dès que le besoin est établi'],
    vigilance: 'Ce portefeuille ne doit pas devenir une orientation durable par défaut.',
  },
  {
    code: 'SP',
    nom: 'Socio-Professionnel',
    description: 'Accompagnement individualisé combinant progression professionnelle et prise en compte de difficultés périphériques.',
    objectif: 'Faire avancer le projet professionnel tout en sécurisant les freins qui perturbent le parcours.',
    public: 'Demandeur ayant plusieurs besoins à coordonner, sans relever nécessairement d’un accompagnement global.',
    criteres: ['Freins périphériques actifs', 'Autonomie à renforcer', 'Projet à construire ou consolider', 'Coordination ponctuelle nécessaire'],
    accompagnement: 'Plan progressif, prescriptions ciblées et articulation avec les partenaires compétents.',
    actions: ['Hiérarchiser les freins', 'Mobiliser les partenaires utiles', 'Maintenir une étape professionnelle réalisable'],
    vigilance: 'Réévaluer régulièrement si la situation relève plutôt d’Emploi, Global ou Travailleur handicapé.',
  },
  {
    code: 'TH',
    nom: 'Travailleurs handicapés',
    description: 'Accompagnement tenant compte du handicap, des capacités, des restrictions et des besoins de compensation.',
    objectif: 'Sécuriser l’accès ou le retour à l’emploi dans un environnement compatible avec la situation de la personne.',
    public: 'Demandeur reconnu travailleur handicapé, bénéficiaire de l’obligation d’emploi ou en cours de reconnaissance.',
    criteres: ['RQTH ou situation assimilée', 'Restriction ou besoin d’aménagement', 'Appui spécialisé utile', 'Projet à vérifier au regard des capacités'],
    accompagnement: 'Coordination avec Cap emploi et mobilisation des aides ou expertises spécialisées lorsque nécessaire.',
    actions: ['Clarifier les restrictions fonctionnelles utiles au projet', 'Vérifier les besoins de compensation', 'Coordonner France Travail, Cap emploi et partenaires'],
    vigilance: 'Ne jamais déduire l’aptitude ou l’inaptitude d’un diagnostic médical ; respecter la confidentialité des données de santé.',
  },
  {
    code: 'GLO',
    nom: 'Global',
    description: 'Accompagnement coordonné lorsque les difficultés sociales et professionnelles sont fortement imbriquées.',
    objectif: 'Traiter simultanément les obstacles sociaux prioritaires et la reprise d’une dynamique vers l’emploi.',
    public: 'Demandeur confronté à des difficultés importantes de logement, santé, mobilité, budget, famille ou accès aux droits.',
    criteres: ['Freins multiples ou critiques', 'Risque de rupture', 'Coordination sociale indispensable', 'Capacité à agir fortement limitée'],
    accompagnement: 'Diagnostic partagé, coordination avec le travail social et plan d’action réaliste par étapes.',
    actions: ['Sécuriser les besoins urgents', 'Identifier le partenaire pilote', 'Conserver un objectif professionnel progressif'],
    vigilance: 'Éviter l’empilement de prescriptions et vérifier qui coordonne effectivement chaque action.',
  },
  {
    code: 'PP',
    nom: 'Parcours professionnalisé',
    description: 'Parcours de transition ou de pré-orientation visant à préciser et sécuriser un projet professionnel.',
    objectif: 'Transformer une idée encore imprécise en projet réaliste, vérifié et organisé en étapes.',
    public: 'Demandeur en reconversion, sans projet défini ou ayant besoin de confronter un projet à la réalité du marché.',
    criteres: ['Projet à préciser', 'Reconversion envisagée', 'Besoin d’exploration métier', 'Compétences à identifier ou développer'],
    accompagnement: 'Exploration, ateliers, immersion, évaluation des compétences puis choix d’une cible et d’un plan.',
    actions: ['Explorer plusieurs pistes', 'Prescrire un atelier interne adapté', 'Confronter le projet par une immersion ou une prestation'],
    vigilance: 'Ne pas engager trop tôt une formation longue avant validation du métier, des prérequis et du financement.',
  },
  {
    code: 'CEJ',
    nom: 'Contrat d’engagement jeune',
    description: 'Accompagnement intensif et contractualisé vers l’emploi et l’autonomie pour les jeunes éligibles.',
    objectif: 'Construire un parcours soutenu composé d’activités utiles, cohérentes et traçables.',
    public: 'Jeune remplissant les critères d’éligibilité du CEJ, après vérification de sa situation et de l’offre d’accompagnement compétente.',
    criteres: ['Âge et situation compatibles', 'Besoin d’accompagnement intensif', 'Engagement dans un programme d’activités', 'Éligibilité à confirmer'],
    accompagnement: 'Programme intensif, suivi des activités et coordination avec la Mission Locale lorsque celle-ci est compétente.',
    actions: ['Vérifier l’éligibilité', 'Construire le programme d’activités', 'Tracer les engagements et réalisations'],
    vigilance: 'Toujours contrôler les conditions réglementaires et les consignes locales avant toute affectation.',
  },
]
